/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.DoctorHistory;
import model.Hospital;
import model.HospitalHistory;
import model.Patient;
import model.PatientHistory;

/**
 *
 * @author sajja
 */
public class NewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewPersonJPanel
     */
    PatientHistory historyP;
    HospitalHistory historyH;
    DoctorHistory history;
    public NewPersonJPanel(PatientHistory historyP, HospitalHistory historyH,DoctorHistory history) {
        initComponents();
        this.historyP=historyP;
        this.historyH = historyH;
        this.history=history;
        populateDropDownValues();
    }

    //NewPersonJPanel(PatientHistory historyP) {
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}

    //NewPersonJPanel(PatientHistory historyP, HospitalHistory historyH, DoctorHistory history) {
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        doctor = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        hosp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        illness = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jHospDropDown1 = new javax.swing.JComboBox<>();
        jCityDropDown1 = new javax.swing.JComboBox<>();
        jDocDropDown = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient's Booking Details");

        jLabel15.setText("Choose Doctor:");

        jLabel16.setText("Patient Name:");

        illness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                illnessActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Patient Illness:");

        jLabel18.setText("Choose Hospital:");

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient Illness", "Choose City", "Choose Hospital", "Choose Doctor"
            }
        ));
        jScrollPane1.setViewportView(tblDetails);

        jLabel23.setText("Choose City");

        jHospDropDown1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jCityDropDown1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jDocDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(illness, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(doctor)
                                    .addComponent(city)
                                    .addComponent(pname)
                                    .addComponent(hosp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHospDropDown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDocDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCityDropDown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(illness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCityDropDown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHospDropDown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDocDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void illnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_illnessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_illnessActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(pname.getText().equals("")||illness.getText().equals("")||city.getText().equals("")||hosp.getText().equals("")||doctor.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter all data !!");

        }else{

            DefaultTableModel model=(DefaultTableModel) tblDetails.getModel();

            String pn=pname.getText();
            String pi=illness.getText();
            String cc=city.getText();
            String ch=hosp.getText();
            String cd=doctor.getText();

            Patient p = historyP.addNewPatient();

            p.setPatientName(pn);
            p.setPIllness(pi);
            p.setChooseCity(cc);
            p.setChooseHospital(ch);
            p.setChooseDoctor(cd);

            historyP.addNewPatient();

            populateTable();

            JOptionPane.showMessageDialog(this, "\n\n Patient Booking confirmed");
            //Cnic.setText("");
            pname.setText("");
            illness.setText("");
            city.setText("");
            hosp.setText("");
            doctor.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void populateTable() {
        
        javax.swing.table.DefaultTableModel model=(javax.swing.table.DefaultTableModel) tblDetails.getModel();
        model.setRowCount(0);
        
        for(Patient p: historyP.getHistoryP()){
            
            Object[] row=new Object[5];
            
            row[0]=p;
            row[1]=p.getPIllness();
            row[2]=p.getChooseCity();
            row[3]=p.getChooseHospital();
            row[4]=p.getChooseDoctor();
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField doctor;
    private javax.swing.JTextField hosp;
    private javax.swing.JTextField illness;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCityDropDown1;
    private javax.swing.JComboBox<String> jDocDropDown;
    private javax.swing.JComboBox<String> jHospDropDown1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pname;
    private javax.swing.JTable tblDetails;
    // End of variables declaration//GEN-END:variables

    private void populateDropDownValues() {
        
        ArrayList<String> cityList = new ArrayList<>();
        
        for(Hospital hs: historyH.getHistory()){
            cityList.add(hs.gethCity());
            
        System.out.println("CITY - " +hs.gethCity() );
        }
        
        jCityDropDown1.setModel(new DefaultComboBoxModel<>(cityList.toArray(new String[0])));
        
        
        
        
        
        ArrayList<String> hospList = new ArrayList<>();
        
        for(Hospital hh: historyH.getHistory()){
            hospList.add(hh.gethName());
            
        System.out.println("HOSPITAL - " +hh.gethName());
        }
        
        jHospDropDown1.setModel(new DefaultComboBoxModel<>(hospList.toArray(new String[0])));
        
        
        
    ArrayList<String> docList = new ArrayList<>();
        
        for(Doctor hd: history.getHistory()){
            docList.add(hd.getDname());
            
        System.out.println("Doctor - " +hd.getDname());
       }
        
      jDocDropDown.setModel(new DefaultComboBoxModel<>(docList.toArray(new String[0])));
   }
}
